export const BRACKET_COPY = {
  back: "Back",
  title: "Knockout Circle",
  competition: "World Cup 2026",
  locked: "LOCKED",
  official: "OFFICIAL",
  liveBracket: "Live Bracket",
  myPicks: "My Picks",
  firstPickHint: "Tap any flag to send that team through to the next round.",
  officialResults: "Official results",
  bracketLocked: "Bracket locked",
  yourBracket: "Your bracket",
  ready: "READY",
  matchesDecided: "matches decided",
  livePanelNote: "The board fills in only when a match is final — no live scores, no clutter. Tap any team to trace its road to the final.",
  buildYourBracket: "BUILD YOUR BRACKET",
  yourPick: "Your pick",
  resultLockedIn: "Result locked in",
  pickNext: "Pick next",
  otherMatchFirst: "Decide the other match first — that empty slot needs a winner before this round opens.",
  promoteTeam: "Tap a team to send it through. Each tap promotes it one round. Finished games are locked in for you.",
  reset: "Reset",
  lockIn: "Lock in bracket →",
  completeToLock: "Complete the bracket to lock",
  bracketLockedHeading: "BRACKET LOCKED",
  yourChampion: "YOUR CHAMPION",
  scoreSoFar: (correct: number, decided: number) => `${correct}/${decided} correct so far`,
  noPredictedMatches: "No predicted matches decided yet",
  scoreLive: "we'll score them live as each match finishes.",
  edit: "Edit",
  toBeDecided: "To be decided",
  awaitingResult: "Awaiting result",
  inTheDraw: "In the draw",
  resultIn: "Result in",
  pickAdvanced: "Your pick advanced ✓",
  knockedOut: "Knocked out ✗",
  pickStillAlive: "Pick still alive",
  pickThisNext: "Pick this next",
  advanced: "Advanced",
  highlightedRoad: "Highlighted: this team's road to the final.",
  championCup: "The champion lifts the cup here.",
  badSlot: "bad slot",
  notSignedIn: "not signed in",
  slotNotPlayable: "slot not yet playable",
  completeFirst: "Complete your bracket first — pick a winner for every match.",
} as const;
