export const DUES_COPY = {
  headerSubline: "All competitions · one balance",
  netPosition: "Net position",
  netNote: "World Cup 2026 and Premier League 2026-27, added up.",
  settleUp: "Settle up",
  planCount: (count: number) => `${count} payments clear every balance`,
  planNote: "The fewest payments that clear every balance. You can log any payment, not only these.",
  logPayment: "Log a payment",
  empty: "Everyone is settled up.",
  boundary: "Cashford records payments. Money still moves over UPI or in cash.",
  syncError: "These balances don’t add up yet. Payment suggestions are paused while the ledger is checked.",
  pendingAnswer: (count: number) => count === 1 ? "1 payment needs your answer" : `${count} payments need your answer`,
} as const;

export const PAYMENT_COPY = {
  title: "Log a payment",
  intro: "Records what moved between two people. It changes those two balances only.",
  payer: "Payer",
  receiver: "Receiver",
  amount: "Amount",
  date: "Date",
  note: "Note (optional)",
  reason: "Reason",
  partial: (payer: string, receiver: string, due: number, amount: number, remaining: number) =>
    `${payer} owes ${receiver} ₹${due.toLocaleString("en-IN")}. Logging ₹${amount.toLocaleString("en-IN")} leaves ₹${remaining.toLocaleString("en-IN")} outstanding.`,
  exact: (amount: number) => `This matches the current ₹${amount.toLocaleString("en-IN")} settle-up suggestion.`,
  overpayment: (extra: number) => `This is ₹${extra.toLocaleString("en-IN")} more than the current suggestion. Cashford will record the amount you entered.`,
  debtorShortcut: (amount: number, receiver: string) => `Log ₹${amount.toLocaleString("en-IN")} paid to ${receiver}`,
  creditorShortcut: (amount: number, payer: string) => `Log ₹${amount.toLocaleString("en-IN")} received from ${payer}`,
  thirdPartyShortcut: (payer: string, receiver: string, amount: number) => `Log ${payer} paying ${receiver} ₹${amount.toLocaleString("en-IN")}`,
  payerSubmit: (amount: number, receiver: string) => `Log ₹${amount.toLocaleString("en-IN")} · send to ${receiver} to confirm`,
  receiverSubmit: (amount: number, payer: string) => `Log ₹${amount.toLocaleString("en-IN")} · send to ${payer} to confirm`,
  thirdPartySubmit: (amount: number) => `Log ₹${amount.toLocaleString("en-IN")} · both people confirm`,
  partialNote: "Partial payments are fine.",
  saveFailure: "Couldn’t log this payment. Try again with the same details.",
  matching: (logger: string) => `${logger} already logged this — open it`,
  looksSameAs: "Looks the same as",
  existingPayment: "the existing payment",
  matchingPayments: (count: number) => count === 1 ? "This matches an existing payment." : `This matches ${count} existing payments.`,
  matchingChanged: "The payment details or matching records changed. Review the updated matches before logging anyway.",
  logAnyway: "Log anyway?",
  pendingReceived: (payer: string, amount: number) => `${payer} says they paid you ₹${amount.toLocaleString("en-IN")}`,
  pendingPayer: (receiver: string, amount: number) => `${receiver} says they received ₹${amount.toLocaleString("en-IN")} from you`,
  thirdPartyPending: (logger: string, payer: string, receiver: string) => `${logger} logged ${payer} paying ${receiver}`,
  confirm: "Confirm",
  dispute: "Dispute",
  waitingOne: (name: string) => `Waiting for ${name} to confirm.`,
  waitingTwo: (first: string, second: string) => `Waiting for ${first} and ${second} to confirm.`,
  immutable: "Once confirmed, the payment facts can’t be edited. A correction gets a visible reversal.",
  disputed: "This payment is disputed and stays out of the balance.",
  confirmAfterDispute: "It happened · confirm",
  cancel: "Cancel record",
  reverse: "Reverse payment",
  reversalIntro: "A reversal keeps the original payment visible and applies the opposite amount after confirmation.",
  reversalFeed: (reason: string) => `Reversal · ${reason}`,
  loggedBy: (name: string, date: string) => `Logged by ${name} · ${date}`,
  share: (url: string) => `Open this Cashford payment to confirm or dispute: ${url}`,
  logFailure: "Couldn’t log this payment.",
  cancelFailure: "Couldn’t cancel this payment.",
  responseFailure: "Couldn’t update this payment.",
  reverseFailure: "Couldn’t reverse this payment.",
} as const;

export const ARCHIVE_COPY = {
  badge: "ARCHIVED",
  notice: "Read-only. These are the screens and rules as they applied in 2026.",
  standings: "Final standings",
  freeze: (date: string) => `Frozen at the final settlement on ${date}.`,
  freezeUnset: "Nothing has settled yet.",
  rules: "Rules as they applied",
  matchesNotice: "Read-only. Every World Cup match, with what you called and what it paid.",
  bracketNotice: "Read-only. Frozen when the World Cup ended.",
  lateMember: "You weren’t in this league during the World Cup.",
  noEntries: "You didn’t enter a World Cup match in this league.",
  noBracket: "You didn’t lock a World Cup bracket.",
  switcherNote: "Archived competitions can be read but not played. Your dues carry across both.",
  plReturn: "Premier League 2026-27",
  tableUnavailable: "Table unavailable",
  tableUnavailableBody: "The Premier League table hasn’t reached Cashford yet.",
  resultUnavailable: "Result unavailable",
  staleTable: (time: string) => `Last updated ${time}. A newer table is on the way.`,
  bracketReadOnly: "World Cup 2026 is archived. Bracket picks are read-only.",
  rulesList: ["Per-match stakes", "Correct predictors split the incorrect predictors’ stakes.", "Each match locked at kickoff.", "Closest-score rules broke an otherwise tied field."],
  archiveMark: "ARCHIVE",
  leagueBalance: "league balance",
  snapshotTitle: "Archive snapshot",
  matchesSettled: "Matches settled",
  yourFinish: "Your finish",
  yourNet: "Your net",
  openLive: (name: string) => ({ label: `Open ${name}`, arrow: "→" }),
  archiveBannerLabel: (competition: string) => `${competition} archive`,
} as const;

export const TRANSITION_COPY = {
  captainHeading: "Premier League 2026-27 is ready",
  captainBody: "Same league, same members, same balance. Your World Cup stays in the archive.",
  anteLabel: "Ante per gameweek",
  consequence: (ante: number) => `Everyone stakes ₹${ante.toLocaleString("en-IN")} a gameweek. Highest score takes the pot.`,
  firstGameweek: (number: number, deadline: string) => `First gameweek: GW${number} · deadline ${deadline}`,
  firstGameweekPrefix: (number: number) => `First gameweek: GW${number} · deadline`,
  cta: "Start Premier League",
  memberHeading: (captain: string) => `Waiting for ${captain} to start the Premier League`,
  memberBody: "Your World Cup archive and league balance are still here.",
  adopted: (league: string) => `Premier League 2026-27 is now active for ${league}.`,
  otherActive: (competition: string) => `${competition} is already active for this league.`,
  preparing: "Premier League setup is still being checked.",
  archivedTarget: (competition: string) => `This league already archived ${competition}. It can’t be started again.`,
  adoptionHeading: (competition: string) => competition,
  alreadyAdopted: "This didn’t go through — it looks like this was already started. Refresh to see the current state.",
  idempotencyMismatch: "That ante doesn’t match your last attempt. Refresh and try again.",
  invalidAnte: "Enter an ante between ₹50 and ₹10,00,000.",
  adoptionFailed: "Couldn’t start this. Try again in a moment.",
  competitionMismatch: "This page is out of date. Refresh and try again.",
  leagueArchived: "This league is archived. It can’t start a new competition.",
  startingLabel: "Starting…",
} as const;

export const PHASE5_UI_COPY = {
  pastMember: "Past member",
  you: "you",
  player: "player",
  activity: "Activity",
  paid: (payer: string, receiver: string) => `${payer} paid ${receiver}`,
  arrow: (payer: string, receiver: string) => `${payer} → ${receiver}`,
  reversed: "reversed",
  saved: "Saved",
  seasonView: "Season view",
  table: "Table",
  gameweeks: "Gameweeks",
  club: "Club",
  played: "Pl",
  goalDifference: "GD",
  points: "Pts",
  correct: "Correct",
  exact: "Exact",
  netRupees: "Net ₹",
  worldCup: "World Cup 2026",
  analytics: "Analytics",
  matches: "Matches",
  bracket: "Bracket",
  finalSettlement: "final settlement",
  yourWorldCup: "Your World Cup",
  finish: (finish: number, correct: number, exact: number) => `Finish #${finish} · ${correct} correct · ${exact} exact`,
} as const;

export const firstDeadlineCopy = (number: number, deadline: string) =>
  `First gameweek: GW${number} · deadline ${deadline}`;
export const firstDeadlinePrefix = (number: number) =>
  `First gameweek: GW${number} · deadline`;
export const createConsequenceCopy = (ante: number) =>
  `Everyone stakes ₹${ante.toLocaleString("en-IN")} a gameweek. Highest score takes the pot.`;
export const beforeTimeCopy = (number: number) =>
  `Your season starts at GW${number}. Earlier gameweeks are read-only history.`;
